[package]
name = "rxargs"
version = "0.1.0"
authors = ["collins.huff"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
